// Generated by CoffeeScript 1.9.1
var easyc, minimist, watcher;

watcher = require('./watch');

easyc = require('./easyc');

minimist = require('minimist');

module.exports = (function() {
  function exports() {}

  exports.run = function*() {
    var argv, options;
    argv = minimist(process.argv.slice(2));
    if (argv.watch) {
      return (yield watcher.watch());
    } else {
      options = {};
      if (argv.fast) {
        options.quickBuild = true;
      }
      return (yield easyc.compile(options));
    }
  };

  return exports;

})();
