// Generated by CoffeeScript 1.8.0
var Compiler;

Compiler = require('./compiler');

module.exports = (function() {
  function exports() {}

  exports.run = function() {
    return Compiler.run();
  };

  return exports;

})();
