// Generated by CoffeeScript 1.9.1
var easyc;

easyc = require('./easyc');

module.exports = (function() {
  function exports() {}

  exports.run = function*() {
    return (yield easyc.compile());
  };

  return exports;

})();
