// Generated by CoffeeScript 1.8.0
var CSS, JS, Route, async, debug, fs, _;

fs = require('fs');

debug = require('debug')('compiler');

async = require('async');

JS = require('./compilers/js');

CSS = require('./compilers/css');

Route = require('./compilers/route');

_ = require('lodash');

module.exports = (function() {
  function exports() {}

  exports.run = function(runCallback) {
    var compile, read, write;
    return async.waterfall([
      read = (function(_this) {
        return function(callback) {
          return fs.readFile('easycompile.json', JSON.stringify(data), callback);
        };
      })(this), compile = (function(_this) {
        return function(config, callback) {
          config = _.map(config, function(value, key) {
            return {
              app: key,
              data: value
            };
          });
          return async.map(config, function(appConfig, callback) {
            return _this.runApp(appConfig.app, appConfig.data, callback);
          }, function(err, results) {
            var result, temp, _i, _len;
            if (results) {
              temp = {};
              for (_i = 0, _len = results.length; _i < _len; _i++) {
                result = results[_i];
                temp[result.app] = result.data;
              }
              results = temp;
            }
            return callback(null, results);
          });
        };
      })(this), write = (function(_this) {
        return function(data, callback) {
          return fs.writeFile('.easyc/output.json', JSON.stringify(data), callback);
        };
      })(this)
    ], (function(_this) {
      return function(err, result) {
        if (err) {
          console.error(err);
        }
        return console.log(result);
      };
    })(this));
  };

  exports.runApp = function(app, config, callback) {
    return async.parallel({
      js: function(callback) {
        if (!config.javascripts) {
          return callback();
        }
        return JS.compile(config.javascripts, callback);
      },
      css: function(callback) {
        if (!config.javascripts) {
          return callback();
        }
        return CSS.compile(config.javascripts, callback);
      },
      routes: function(callback) {
        if (!config.routing) {
          return callback();
        }
        return Route.compile(config.routing, callback);
      }
    }, function(err, results) {
      return callback(err, results);
    });
  };

  return exports;

})();
