// Generated by CoffeeScript 1.9.1
var Dependencies, _;

_ = require('lodash');

Dependencies = (function() {
  function Dependencies() {
    this.store = [];
  }

  Dependencies.prototype.add = function(files) {
    var file, i, len, results;
    if (!_.isArray(files)) {
      files = [files];
    }
    results = [];
    for (i = 0, len = files.length; i < len; i++) {
      file = files[i];
      results.push(this.store.push(file));
    }
    return results;
  };

  Dependencies.prototype.getAll = function() {
    return _.uniq(this.store);
  };

  Dependencies.prototype.toJSON = function() {
    return this.getAll();
  };

  return Dependencies;

})();

module.exports = Dependencies;
