// Generated by CoffeeScript 1.8.0
var Compiler, fs, util, _;

fs = require('co-fs-plus');

Compiler = require('./compiler');

_ = require('lodash');

util = require('util');

module.exports = (function() {
  function exports() {}

  exports.compile = function*() {
    var config, results;
    config = JSON.parse((yield fs.readFile('easycompile.json', 'utf-8')));
    results = (yield Compiler.run(config));
    (yield fs.mkdirp('.easyc/'));
    return (yield fs.writeFile('.easyc/data.json', JSON.stringify(results, null, 2)));
  };

  exports.load = function*() {
    var e;
    if (!this._cache) {
      try {
        this._cache = JSON.parse((yield fs.readFile('.easyc/data.json', 'utf-8')));
      } catch (_error) {
        e = _error;
        this._cache = (yield this.compile());
      }
    }
    return this._cache;
  };

  exports.setProduction = function(_production) {
    this._production = _production != null ? _production : true;
  };

  exports.getEnv = function() {
    if (this._production) {
      return 'prod';
    } else {
      return 'dev';
    }
  };

  exports.getJavascripts = function*(app, packs) {
    var config, pack, _ref;
    config = (yield this.load());
    if ((config != null ? (_ref = config[app]) != null ? _ref.javascripts : void 0 : void 0) == null) {
      return [];
    }
    if (!util.isArray(packs)) {
      if (typeof packs === 'string') {
        packs = [packs];
      } else {
        packs = Object.keys(config[app].javascripts);
      }
    }
    return _.flatten((function() {
      var _i, _len, _ref1, _results;
      _results = [];
      for (_i = 0, _len = packs.length; _i < _len; _i++) {
        pack = packs[_i];
        _results.push(((_ref1 = config[app].javascripts[pack]) != null ? _ref1[this.getEnv()] : void 0) || []);
      }
      return _results;
    }).call(this));
  };

  exports.getStylesheets = function*(app, packs) {
    var config, pack, _ref;
    config = (yield this.load());
    if ((config != null ? (_ref = config[app]) != null ? _ref.stylesheets : void 0 : void 0) == null) {
      return [];
    }
    if (!util.isArray(packs)) {
      if (typeof packs === 'string') {
        packs = [packs];
      } else {
        packs = Object.keys(config[app].stylesheets);
      }
    }
    return _.flatten((function() {
      var _i, _len, _ref1, _results;
      _results = [];
      for (_i = 0, _len = packs.length; _i < _len; _i++) {
        pack = packs[_i];
        _results.push(((_ref1 = config[app].stylesheets[pack]) != null ? _ref1[this.getEnv()] : void 0) || []);
      }
      return _results;
    }).call(this));
  };

  return exports;

})();
