// Generated by CoffeeScript 1.9.3
var args, co, easyc;

easyc = require('../lib/easyc');

co = require('co');

args = process.argv.slice(2);

co(function*() {
  var e;
  try {
    return (yield easyc.compile({
      quickBuild: true,
      onlyApp: args[0],
      onlyPack: args[1],
      onlyPart: args[2]
    }));
  } catch (_error) {
    e = _error;
    return console.error(e.stack);
  }
})();
