// Generated by CoffeeScript 1.9.3
var co, easyc;

easyc = require('../lib/easyc');

co = require('co');

co(function*() {
  var e, ref, ref1, ref2;
  try {
    return (yield easyc.compile({
      quickBuild: true,
      onlyApp: process.env.app ? (ref = process.env.app) != null ? ref.split(',') : void 0 : [],
      onlyPack: process.env.pack ? (ref1 = process.env.pack) != null ? ref1.split(',') : void 0 : [],
      onlyPart: process.env.part ? (ref2 = process.env.part) != null ? ref2.split(',') : void 0 : []
    }));
  } catch (_error) {
    e = _error;
    return console.error(e.stack);
  }
})();
