// Generated by CoffeeScript 1.8.0
var coffee, fs, path;

fs = require('co-fs-plus');

path = require('path');

coffee = require('coffee-script');

module.exports = (function() {
  function exports() {}

  exports.compilesTo = 'js';

  exports.compile = function*(pack, input, options) {
    var compiled, content, e, inputWeb, map, output, outputWeb;
    output = path.resolve(options.buildRoot, pack, input) + '.js';
    input = path.resolve(options.root, input);
    outputWeb = path.relative(options.webRoot, output);
    inputWeb = path.relative(options.webRoot, input);
    content = (yield fs.readFile(input, "utf-8"));
    try {
      compiled = coffee.compile(content, {
        header: false,
        bare: true,
        sourceMap: true,
        sourceFiles: ["/" + inputWeb],
        filename: input
      });
    } catch (_error) {
      e = _error;
      throw e;
    }
    compiled.js += "\n//# sourceMappingURL=" + (path.basename(outputWeb)) + ".map";
    map = JSON.parse(compiled.v3SourceMap);
    map.file = path.basename(output);
    (yield fs.mkdirp(path.dirname(output)));
    (yield fs.writeFile(output, compiled.js));
    (yield fs.writeFile(output + ".map", JSON.stringify(map)));
    return path.relative(options.root, output);
  };

  return exports;

})();
