// Generated by CoffeeScript 1.8.0
module.exports = (function() {
  function exports() {}

  exports.compile = function(config, callback) {
    console.log('js compiler', config);
    return callback(null, config);
  };

  return exports;

})();
