// Generated by CoffeeScript 1.8.0
var path;

path = require('path');

module.exports = (function() {
  function exports() {}

  exports.compile = function(pack, files, options) {
    console.log('js compiler');
    console.log(pack, files, options);
    return files;
  };

  return exports;

})();
