// Generated by CoffeeScript 1.8.0
module.exports = (function() {
  function exports() {}

  exports.compile = function(config) {
    console.log('route compiler', config);
    return config;
  };

  return exports;

})();
