// Generated by CoffeeScript 1.9.1
var debug, fs, minify, path, regex, regexg;

fs = require('co-fs-plus');

path = require('path');

minify = require('html-minifier').minify;

debug = require('debug')('compiler:template');

regex = /templateUrl:[\s]*?("([^"\\]*(\\.[^"\\]*)*)"|\'([^\'\\]*(\\.[^\'\\]*)*)\')/i;

regexg = /templateUrl:[\s]*?("([^"\\]*(\\.[^"\\]*)*)"|\'([^\'\\]*(\\.[^\'\\]*)*)\')/gi;

module.exports = (function() {
  function exports(pack, config) {
    this.pack = pack;
    this.config = config;
    this.cache = {};
    this.templateCount = 0;
  }

  exports.prototype.parseAndAddFromFile = function*(file) {
    var content, i, len, match, matches, results, template;
    content = (yield fs.readFile(file, 'utf-8'));
    matches = content.match(regexg);
    if (!(matches != null ? matches.length : void 0)) {
      return;
    }
    results = [];
    for (i = 0, len = matches.length; i < len; i++) {
      match = matches[i];
      if (this.cache[match] != null) {
        continue;
      }
      try {
        match = match.match(regex);
        match = match[2] || match[4];
        file = match;
        if (match.charAt(0) === '/') {
          file = match.substr(1);
        }
        file = path.resolve(this.config.webRoot, file);
        template = (yield fs.readFile(file, 'utf-8'));
        results.push(this.addTemplateToCache(match, template));
      } catch (_error) {}
    }
    return results;
  };

  exports.prototype.addTemplateToCache = function(file, template) {
    this.cache[file] = minify(template, {
      removeComments: true,
      collapseWhitespace: true
    });
    return this.templateCount++;
  };

  exports.prototype.hasTemplates = function() {
    return this.templateCount > 0;
  };

  exports.prototype.getTemplatesList = function() {
    var file, list;
    list = [];
    for (file in this.cache) {
      list.push(file);
    }
    return list;
  };

  exports.prototype.writeCache = function*() {
    var content, file, output, template;
    debug("Writing template cache");
    output = path.resolve(this.config.buildRoot, this.pack + ".cache.js");
    content = "angular.module(" + (JSON.stringify(this.config.angularTemplates)) + ", []).run(['$templateCache', function($templateCache){\n  " + (((function() {
      var ref, results;
      ref = this.cache;
      results = [];
      for (file in ref) {
        template = ref[file];
        results.push("$templateCache.put(" + (JSON.stringify(file)) + ", " + (JSON.stringify(template)) + ");");
      }
      return results;
    }).call(this)).join("\n  ")) + "\n}]);";
    (yield fs.mkdirp(path.dirname(output)));
    (yield fs.writeFile(output, content));
    return output;
  };

  return exports;

})();
